# Generated by Django 3.0.5 on 2020-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzaApp', '0002_auto_20200525_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('active', models.BooleanField(default=True)),
                ('pizzas', models.ManyToManyField(blank=True, null=True, to='pizzaApp.Pizzas')),
            ],
        ),
    ]
