# Generated by Django 3.0.5 on 2020-06-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200601_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
