# Generated by Django 3.0.5 on 2020-06-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_changed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
