# Generated by Django 3.0.5 on 2020-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cheese',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crust',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fruits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mushrooms',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mushrooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('clock', models.DateTimeField(blank=True, null=True)),
                ('clockfinish', models.DateTimeField(blank=True, db_column='clockFinish', null=True)),
                ('orderitems', models.TextField(blank=True, db_column='orderItems', null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('payment', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=40, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pizzas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sauce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saucebase',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saucebase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vegetables',
                'managed': False,
            },
        ),
    ]
